# This is the file containing most of the text appearing in game.
# It can easily be modified or translated without having to mess with the code.

#eris.py
UNKNOWN_CMD = "Unknown command: %s\r\n"
ENTER_GAME = "%s enters the game.\r\n\r\n> "
LEAVE_GAME = "%s leaves the game.\r\n\r\n> "

# login.py
NAME_INPUT = "Please enter your name: "
NAME_NO = "You will need a name.\r\n\r\n"
NAME_ALPHA = "You name can only contain letters.\r\n"
NAME_BAD = "This name is not allowed. Choose something else.\r\n"
NAME_IS = "Your name is %s\r\n"
WELCOME = "Welcome in, %s\r\n"
WELCOME_NEW = "New player! Welcome to ErisMUD!\r\n"
PASSWORD = "Password: "
PASSWORD_WRONG = "Wrong password.\r\n"
PASSWORD_CONFIRM = "\r\nConfirm your password: "
PASSWORD_MISMATCH = "Passwords don't match.\r\n"
ANSI = "\r\nDo you want ANSI colors? (yes, no) "
BANNED = "You have been banned. Get out.\r\n"
LOGIN = "\r\nYou've logged in successfully!\r\n\r\n"
LOGIN_ALREADY_IN = "This player is already in.\r\n"
NEW_PLAYER = "\r\nNew player created!\r\n"
PRESS_ENTER = "Press <enter> to join.\r\n >"
EMAIL = "What is your email address?\r\n"
EMAIL_BAD = "Invalid format for an email address.\r\n"
ERROR_CRITICAL = "Something is wrong, contact the admin.\r\n"

# actions.py
DESC_SET = "Description set.\r\n"
DROP = "%s dropped %s.\r\n"
DROP_CANT = "You cannot drop this.\r\n"
EMOTE_DEFAULT = "You feel emotional.\r\n"
EMOTE = "Emote: %s %s \r\n"
EXITS = "Exits:"
GET = "You pick up %s.\r\n"
NOT_HERE = "This is not here.\r\n"
GIVE = "You give %s to %s.\r\n"
GIVES = " gives %s to %s"
DONT_GO = "You don't go anywhere.\r\n"
CANT_MOVE = "You can't move that way.\r\n"
CANT_SEE = "You do not see that here.\r\n"
NO_EXIT = "No exit this way.\r\n"
LEAVE = " leaves %s."
ENTER = " enters the room."
HELP_TOPICS = "The following help topics exist:\r\n"
NO_HELP = "Help is not available on this topic.\r\n"
INVENTORY = "Inventory\r\n"
LOOKS_AT = " looks at "
YOU_SAY = "You say: %s \r\n"
SAYS = "says: %s"
WHO = "The following players are logged on:\r\n"
PLAYER_NOT_FOUND = "This person is not here.\r\n"
SYNTAX_GIVE = "Correct syntax is: give <item> to <player>\r\n"
SYNTAX_ANSI = "Syntax:\r\nsetansi [off|on]\r\n"

# admin.py
ADDROOM = "Your new room has id #%d.\r\n"
ADDROOM_ERR = "Something didn't work.\r\n"
BAN = "%s has been banned and will not be able to log back in. Use <unban> to undo.\r\n"
BAN_ERR = "Impossible to ban that player.\r\n"
UNBAN = "%s has been unbanned.\r\n"
UNBAN_ERR = "Impossible to unban that player.\r\n"
DELROOM = "Room #%s and all of its links have been deleted.\r\n"
DELROOM_ERR = "Unable to find this room.\r\nCorrect syntax: delroom <room ID>\r\n"
ADDLINK = "New link added.\r\n"
ADDLINK_ERR = "Correct syntax: addlink <origin> <destination> <direction>\r\n"
DELLINK = "Link #%s has been deleted.\r\n"
DELLINK_ERR = "This link does not exist.\r\nCorrect syntax: dellink <link ID>\r\n"
SETSHORT = "Short description changed.\r\n"
SETSHORT_ERR = "Unable to set the short description of this room.\r\n"
SETLONG = "Long description changed.\r\n"
SETLONG_ERR = "Unable to set the long description of this room.\r\n"
ADDHELP = "Help database updated.\r\n"
ADDHELP_ERR = "Correct syntax: addhelp <title> <documentation>\r\n"
GOTO = "You teleport to the new place.\r\n"
GOTO_ERR = "This room does not exist.\r\n"
ADDITEM = "Item %s has been created with ID #%s.\r\n"
ADDITEM_ERR = "The object needs a name.\r\n"
DELITEM = "%s and all its instances have been destroyed.\r\n"
DELITEM_ERR = "This object does not exist.\r\n"
ITEMDESC = "Description set on %s.\r\n"
ITEMDESC_ERR = "This object does not exist.\r\n@itemdesc <item name> <description>"
CLONE = "%s has been cloned.\r\n"
CLONE_ERR = "No such object or NPC.\r\n"
DESTOBJ = "Object Instance #%s has been destroyed.\r\n"
DESTOBJ_ERR = "Object Instance #%s does not exist.\r\n"
DESTNPC = "NPC Instance #%s has been destroyed.\r\n"
DESTNPC_ERR = "NPC Instance #%s does not exist.\r\n"
ADDNPC = "NPC %s has been created with ID #%s.\r\n"
ADDNPC_ERR = "The NPC needs a name.\r\n> "
NPCDESC = "Description set on %s.\r\n"
NPCDESC_ERR = "This NPC does not exist.\r\nCorrect syntax: npcdesc <name> <description>\r\n"
DELNPC = "NPC #%s has been deleted.\r\n"
DELNPC_ERR = "This NPC does not exist.\r\n"
RIDPLAYER = "Player %s has been completely wiped out of the system.\r\n"
RIDPLAYER_ERR = "Player %s not found in the database.\r\n"
EDIG = "New room created %s of here.\r\n"
EDIG_ERR1 = "Usage: edig <exit> <room name/short description>\r\n"
EDIG_ERR2 = "This exit already exists here.\r\n"
EMAIL = "Correct syntax:\r\nemail <name>\r\n"
EMAIL_ERR = "Player not found.\r\n"
IMPORT = "Map imported successfully.\r\n"
IMPORT_ERR1 = "Usage: import <file> <first room> <direction>\r\n"
IMPORT_ERR2 = "Connected room not found on the map.\r\n"







